title: Yilin(Harry) Lu's Homepage
page-top-title: Yilin(Harry) Lu
top-section-bg-text: HCI and Visualization Nerd
home-subtitle: Yilin(Harry) Lu&ensp;|&ensp;鲁亦霖
copyright-text: '&copy; Yilin(Harry) Lu 2023-2024. All Rights Reserved.'
